Moved start and stop script to control script.

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,6 +2,7 @@
 
 STOPTIMEOUT=10
 FMT="%a %b %d %Y %H:%M:%S GMT%z (%Z)"
+LOG_FILE="${OPENSHIFT_PLAY2LOG_LOG_DIR}play.log"
 
 function is_play_service_running() {
     if [ -f ${OPENSHIFT_REPO_DIR}RUNNING_PID ]; then
@@ -14,6 +15,58 @@ function is_play_service_running() {
     return 1
 }
 
+function kill_app {
+	COMMAND="$1"
+	# try 5 times to kill it
+	for c in `seq 1 5`; do
+		echo "Trying to kill proccess, attempt number $c" >> $LOG_FILE
+		echo "$COMMAND" >> $LOG_FILE
+		bash -c "$COMMAND &>> $LOG_FILE 2>&1" &> /dev/null
+		sleep $c
+		#killed it
+		if [[ -z `ps -A | grep ' java$'` ]]; then
+			if [[ -f "RUNNING_PID" ]]; then
+				rm RUNNING_PID
+			fi
+			popd > /dev/null
+			exit 0
+		fi
+	done
+}
+
+function load_config {
+	# check needed vars
+	if [[ -z $OPENSHIFT_REPO_DIR ]]; then
+		echo "Error: OPENSHIFT_REPO_DIR not defined"
+		return 1
+	fi
+
+	PLAY_PARAMS=""
+
+	PLAY_CONFIG_FILE="${OPENSHIFT_REPO_DIR}conf/openshift.conf"
+
+	if [[ -f $PLAY_CONFIG_FILE ]]; then
+
+		function read_conf {
+			local key=$1
+			local default=$2
+			local result=`grep "^$key[ |=]" $PLAY_CONFIG_FILE`
+
+			# key not found
+			if [[ -z "$result" ]]; then
+				echo $default
+			else
+				result=`echo "$result" | grep -oP "=.*" | cut -b 1 --complement`
+				echo $result
+			fi
+		}
+
+		PLAY_PARAMS=$(read_conf "openshift.play.params" $PLAY_PARAMS)
+	fi
+
+	return 0
+}
+
 function status() {
     if is_play_service_running; then
         client_result "Application is running"
@@ -24,11 +77,60 @@ function status() {
 
 
 function start() {
-    #${OPENSHIFT_PLAY2JAVA_DIR}.openshift/action_hooks/start
+    	# loads $PLAY_PARAMS
+	load_config
+
+	LOG_FILE="${OPENSHIFT_PLAY2JAVA_LOG_DIR}play.log"
+
+	if [ ! -f ${OPENSHIFT_REPO_DIR}target/start ]; then
+		echo "Info: Application not deployed yet, deploying now" >> $LOG_FILE		
+		nohup bash -c "${OPENSHIFT_PLAY2JAVA_DIR}.openshift/action_hooks/build &>> ${LOG_FILE}"
+		nohup bash -c "${OPENSHIFT_PLAY2JAVA_DIR}.openshift/action_hooks/deploy &>> ${LOG_FILE}"
+	fi
+
+	APP_COMMAND="${OPENSHIFT_REPO_DIR}target/start $PLAY_PARAMS "\
+		"-Dhttp.port=${OPENSHIFT_PLAY2JAVA_PORT} "\
+		"-Dhttp.address=${OPENSHIFT_PLAY2JAVA_IP} "\
+		"-Dconfig.resource=openshift.conf"
+
+	echo $APP_COMMAND &>> $LOG_FILE
+	nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
 }
 
 function stop() {
-    #${OPENSHIFT_PLAY2JAVA_DIR}.openshift/action_hooks/start
+	pushd "$OPENSHIFT_PLAY2JAVA_DIR" > /dev/null
+
+	#kill play if it was running
+	if [[ -f "RUNNING_PID" ]]; then
+
+		pid=`cat RUNNING_PID`
+		echo "Stopping play application" >> $LOG_FILE
+
+		if [[ -n $pid ]]; then
+			#try to kill it nicely
+			kill_app "kill -SIGTERM $pid"
+			#try to kill it harshly
+			kill_app "kill -SIGKILL $pid"
+		fi
+	fi
+
+	#it survived, try to kill java
+	if [[ -n `ps -A | grep java` ]]; then
+		echo "Stopping java proccess" >> $LOG_FILE
+		#try to kill it nicely
+		kill_app "pkill -SIGTERM java"
+		#try to kill it harshly
+		kill_app "pkill -SIGKILL java"
+	fi
+
+	#couldn't kill it
+	if [[ -n `ps -A | grep java` ]]; then
+		echo "Error: could not stop play application, error executing 'pkill java'" >> $LOG_FILE
+		popd
+		exit 1
+	fi
+
+	popd > /dev/null
 }
 
 function restart() {
