Improved scripts

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -27,22 +27,18 @@ function start() {
     logf="${OPENSHIFT_PLAY2JAVA_LOG_DIR}play.log"
     pushd "$OPENSHIFT_PLAY2JAVA_DIR" > /dev/null
     {
-        if [ -f "${OPENSHIFT_PLAY2JAVA_DIR}versions/play-$PLAY_VERSION/play" ]; then
-            echo "`date +"$FMT"`: Starting application '$OPENSHIFT_APP_NAME' from versions/play-$PLAY_VERSION..."
+	    echo "`date +"$FMT"`: Starting application '$OPENSHIFT_APP_NAME' from versions/play-$PLAY_VERSION..."
 
-            nohup "${OPENSHIFT_PLAY2JAVA_DIR}versions/play-$PLAY_VERSION/play" -c "${OPENSHIFT_REPO_DIR}.openshift/action_hooks/start" >> $logf 2>&1 &
+	    nohup "${OPENSHIFT_REPO_DIR}.openshift/action_hooks/start" >> $logf 2>&1 &
 
-            ret=$?
-            npid=$!
-            if [ $ret -eq 0 ]; then
-                echo "$npid" > "${OPENSHIFT_PLAY2JAVA_DIR}pid/play.pid"
-            else
-                echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
-                exit $ret
-            fi
-        else
-            echo "WARN: Could not find the compiled application versions/play-$PLAY_VERSION, will not start"
-        fi
+	    ret=$?
+	    npid=$!
+	    if [ $ret -eq 0 ]; then
+		echo "$npid" > "${OPENSHIFT_PLAY2JAVA_DIR}pid/play.pid"
+	    else
+		echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
+		exit $ret
+	    fi
     } >> $logf
 }
 
