Now modellign after nginx-cartridge

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,32 +1,119 @@
-#!/bin/bash -eu
+#!/bin/bash
 
+STOPTIMEOUT=10
+FMT="%a %b %d %Y %H:%M:%S GMT%z (%Z)"
+
+function is_play_service_running() {
+    if [ -f $OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid ]; then
+        play_pid=$( cat $OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid 2> /dev/null )
+        if `ps --pid $play_pid 2>&1`; then
+            return 0
+        fi
+    fi
+
+    return 1
+}
+
+function status() {
+    if is_play_service_running; then
+        client_result "Application is running"
+    else
+        client_result "Application is not running"
+    fi
+}
+
+
+function start() {
+    logf="$OPENSHIFT_PLAY2JAVA_LOG_DIR/play.log"
+    pushd "$OPENSHIFT_PLAY2JAVA_DIR" > /dev/null
+    {
+        if [ -f "versions/play-$PLAY_VERSION" ]; then
+            echo "`date +"$FMT"`: Starting application '$OPENSHIFT_APP_NAME' from versions/play-$PLAY_VERSION..."
+
+            nohup "versions/$PLAY_VERSION/play" -c "${OPENSHIFT_REPO_DIR}.openshift/action_hooks/start" >> $logf 2>&1 &
+
+            ret=$?
+            npid=$!
+            if [ $ret -eq 0 ]; then
+                echo "$npid" > "$OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid"
+            else
+                echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
+                exit $ret
+            fi
+        else
+            echo "WARN: Could not find the compiled application versions/play-$PLAY_VERSION, will not start"
+        fi
+    } >> $logf
+}
+
+function stop() {
+    if [ -f $OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid ]; then
+        play_pid=$( cat $OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid 2> /dev/null )
+    fi
+
+    if [ -n "$play_pid" ]; then
+        logf="$OPENSHIFT_PLAY2JAVA_LOG_DIR/play.log"
+        echo "`date +"$FMT"`: Stopping application '$OPENSHIFT_APP_NAME' ..." >> $logf
+        /bin/kill $play_pid
+        ret=$?
+        if [ $ret -eq 0 ]; then
+            TIMEOUT="$STOPTIMEOUT"
+            while [ $TIMEOUT -gt 0 ] && is_play_service_running ; do
+                /bin/kill -0 "$play_pid" >/dev/null 2>&1 || break
+                sleep 1
+                let TIMEOUT=${TIMEOUT}-1
+            done
+        fi
+
+        echo "`date +"$FMT"`: Stopped Play application '$OPENSHIFT_APP_NAME'" >> $logf
+        rm -f $OPENSHIFT_PLAY2JAVA_DIR/pid/play.pid
+    else
+        echo "Warning: Application '$OPENSHIFT_APP_NAME' application exists without a pid file.  Use force-stop to kill." 1>&2
+    fi
+}
+
+function restart() {
+    stop
+    start
+}
+
+function compile() {
+    echo
+}
+
+function dist() {
+    echo
+}
+
+function tidy() {
+  client_message "Emptying log dir: $OPENSHIFT_PLAY2JAVA_LOG_DIR"
+  shopt -s dotglob
+  rm -rf $OPENSHIFT_PLAY2JAVA_DIR/logs/*
+  rm -rf $OPENSHIFT_PLAY2JAVA_DIR/tmp/*
+}
+
+#
+#  main():
+#
+
+# Ensure arguments.
+if ! [ $# -eq 1 ]; then
+    echo "Usage: $0 [start|restart|stop|status|compile|dist|tidy]"
+    exit 1
+fi
+
+# Source utility functions.
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
-function start {
-  echo "Starting Play 2 Java cartridge"
-  ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/start
-}
-
-function stop {
-  echo "Stopping Play 2 Java cartridge"
-  ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop
-}
-
-function catchall {
-  echo "Not yet implemented"
-}
-
+# Handle commands.
 case "$1" in
-  start)                start ;;
-  stop)                 stop ;;
-  status)      status ;;
-  reload)      catchall ;;
-  tidy)        catchall ;;
-  pre-build)   catchall ;;
-  build)       catchall ;;
-  deploy)      catchall ;;
-  post-deploy) catchall ;;
-  *)           exit 0
+    start)               start       ;;
+    restart)    	 restart     ;;
+    stop)  		 stop        ;;
+    status)              status      ;;
+    compile)		 compile     ;;
+    dist)		 dist        ;;
+    tidy)                tidy        ;;
+    *) exit 0;
 esac
 
-exit 0
